---
# Set to 'true' to configure the Dock via dockutil.
configure_dotfiles: true
configure_osx: false

configure_dock: false

dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - gh
  - gpg
  - node
  - nvm
  - cowsay
  - openssl
  - pv
  - wget
  - fish
  - starship
  - tmux
  - neovim
  - pnpm
  - zoxide
  - bat
  - fzf
  - fortune
  - neofetch
  - lolcat
  - btop
  - thefuck
  - stow
  - yabai
  - skhd
homebrew_taps:
  - koekeishiya/formulae

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - arc
  - raycast
  - adobe-creative-cloud
  - mountain-duck
  - 1password
  - 1password-cli
  - balenaetcher
  - cyberduck
  - dbngin
  - devkinsta
  - fantastical
  - logitech-g-hub
  - nvidia-geforce-now
  - obsidian
  - qbittorrent
  - setapp
  - visual-studio-code
  - wezterm
  - docker
  - font-fira-code-nerd-font

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
