---
- name: Download dotfiles repository.
  git:
    repo: 'git@github.com:haydenkoch/dotfiles.git'
    dest: ~/.dotfiles
    version: main

- name: Stow tasks/dotfiles
  shell: stow -t ~ *
  args:
    chdir: ~/.dotfiles 
